apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-deployment
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roadmap
  template:
    metadata:
      labels:
        app: roadmap
    spec:
      containers:
      - name: roadmap-container
        image: 800770414458.dkr.ecr.us-east-2.amazonaws.com/ivolve-app-repo:roadmap-4
        ports:
        - containerPort: 8080
    