@Library('my-shared-library@main') _

buildPipeline(
    serviceName: 'auth',
    servicePath: 'src_code/auth-service',
    ecrRepoUrl: '800770414458.dkr.ecr.us-east-2.amazonaws.com/ivolve-app-repo', // هنبقى نعدل ده برقم حسابك بعدين
    githubRepo: 'Abdelrahmanelhelw/CloudDevOpsProject' 
)