@Library('my-shared-library@main') _

buildPipeline(
    serviceName: 'roadmap',
    servicePath: 'src_code/roadmap-service',
    ecrRepoUrl: '123456789.dkr.ecr.us-east-2.amazonaws.com/ivolve-app-repo',
    githubRepo: 'Abdelrahmanelhelw/CloudDevOpsProject'
)