apiVersion: apps/v1
kind: Deployment
metadata:   
  name: frontend-deployment
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata: 
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: <your-ecr-repo-url>/frontend:latest
          ports:
          - containerPort: 3000
          env:
          - name: AUTH_SERVICE_URL
            valueFrom:
              configMapKeyRef:  
                name: ivolve-configmap
                key: AUTH_SERVICE_URL
          - name: ROADMAP_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: ivolve-configmap
                key: ROADMAP_SERVICE_URL
