@Library('my-shared-library@main') _

buildPipeline(
    serviceName: 'auth',
    servicePath: 'auth-service',
    ecrRepoUrl: '123456789.dkr.ecr.us-east-2.amazonaws.com/ivolve-app-repo', // هنبقى نعدل ده برقم حسابك بعدين
    githubRepo: 'Abdelrahmanelhelw/CloudDevOpsProject' 
)