plugin: aws_ec2

#Region of the Jenkins Server

regions:
  - us-east-1

#Conditions to filter the instances based on tags and state
filters:
  # we want to get only the instances that have the tag "Role" with the value "Jenkins"
  "tag:Role": "Jenkins"
  
  # we want to get only the instances that are in the "running" state
  instance-state-name: "running" 

#how to group the instances , based on their tags
keyed_groups:
  # create a group based on the 'Role' tag
  - key: tags.Role
    prefix: tag
    separator: "_"

# (optional but important) to ensure it fetches the public IP instead of the private IP
compose:
  ansible_host: public_ip_address

